from pathlib import Path
from PIL import Image,ImageDraw,ImageFont
import json,hashlib
P=Path(__file__).resolve().parent;font=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',24);small=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',18)
for style in ['textured','gray']:
 im=Image.new('RGB',(2240,808),(235,235,230));draw=ImageDraw.Draw(im)
 for i,(name,title) in enumerate([('before','ORIGINAL POSE'),('pose-preview','POSE PREVIEW: world Y -0.127117 scene units')]):
  draw.text((20+1120*i,12),title,fill=(20,20,20),font=font);im.paste(Image.open(P/f'offline-{name}-close-{style}.png').convert('RGB'),(1120*i,48))
 draw.text((20,757),f'{style.upper()} | Original detailed support and branch geometry. Same actual QA close camera: [4.7,1.25,-21.7] -> [1.8,0,-25.45]',font=small,fill=(20,20,20));draw.text((20,783),'Offline fixed-light GLB-material pose comparison only; production water/substrate shader and browser behavior are not reproduced.',font=small,fill=(20,20,20));im.save(P/f'offline-pose-compare-{style}.png')
source=Path('/workspace/scratch/56bf13a306b9/coral-3d');candidate=P.parents[1];paths=['dist/assets/swim-routes.json','dist/fish-motion.js','dist/fish-population.js','dist/fish-surface.js'];hashes=[]
for p in paths:
 a=hashlib.sha256((source/p).read_bytes()).hexdigest();b=hashlib.sha256((candidate/p).read_bytes()).hexdigest();assert a==b;hashes.append({'path':p,'source_sha256':a,'pose_candidate_sha256':b,'unchanged':True})
oldfile=source/'evidence/fish-surface-oct7/geometry-motion-check.json';old=json.loads(oldfile.read_text());report={'scope':'Preserves the existing sampled vertical roof-clearance criterion for the unchanged six fish routes; not a new whole-body or continuous collision certificate.','distance_units':'uncalibrated scene units','changed_target':'Corridor_Distant_Linked_03','world_y_downshift_scene_units':.12711730762552115,'argument':'For any fixed (x,z), pure downward translation leaves the target footprint fixed and changes its highest vertical intersection height T to T-delta. Every other terrain height O is unchanged, so max(O,T-delta) <= max(O,T). Therefore unchanged fish-center height minus sampled roof cannot decrease at any previously checked footprint point. The same five-point footprint checks remain no worse under this isolated change.','preserved_existing_check':'qa-life.mjs checks fish center plus x/z offsets [±0.22,0] and [0,±0.22] against highest triangle roof every 0.5 simulated seconds within its 164-second sampled run. This does not certify articulated full-body swept collision.','fish_route_and_motion_hashes':hashes,'historical_report_path':str(oldfile),'historical_report_sha256':hashlib.sha256(oldfile.read_bytes()).hexdigest(),'historical_scope':old['scope'],'historical_minimum_vertical_clearances':[{'name':f['name'],'minimum_clearance_scene_units':f['minClearance']}for f in old['fish']],'historical_numeric_caveat':'The historical report does not embed its geometry source hash; its numbers are reference values, not newly measured current-pose minima. The monotonicity statement applies to the isolated old-pose/new-pose comparison independent of those values.','new_worldwide_route_test_run':False,'new_full_body_collision_test_run':False}
(P/'fish-roof-monotonicity.json').write_text(json.dumps(report,indent=2)+'\n')
manifest={f.name:{'sha256':hashlib.sha256(f.read_bytes()).hexdigest(),'bytes':f.stat().st_size}for f in P.iterdir()if f.name.startswith('offline-')or f.name in ['render_offline_pose.py','package_offline_pose.py','fish-roof-monotonicity.json']}
(P/'offline-pose-artifacts.json').write_text(json.dumps(manifest,indent=2)+'\n')
