import {refineFish03} from './dist/fish-surface.js';
import {composeReef} from './dist/inhabited-reef.js';
import {sampleSwimRoute as baselineSample} from './evidence/life-oct7/baseline-fish-motion.js';
import fs from 'node:fs';import assert from 'node:assert/strict';import * as T from 'three';import{GLTFLoader}from'./dist/vendor/GLTFLoader.js';import{sampleSwimRoute}from'./dist/fish-motion.js';import{addCompanionFish}from'./dist/fish-population.js';import{createRequire}from'node:module';const require=createRequire(import.meta.url);const{loadImage}=require('@napi-rs/canvas');globalThis.self=globalThis;globalThis.createImageBitmap=async b=>loadImage(Buffer.from(await b.arrayBuffer()));
const isBaseline=process.argv.includes('--baseline');const sample=isBaseline?baselineSample:sampleSwimRoute;const b=fs.readFileSync('source-model.glb');const{scene}=await new Promise((r,j)=>new GLTFLoader().parse(b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength),'',r,j));const extra=fs.readFileSync('dist/assets/inhabited/bf93ec504f8f2fc3/pilot.glb');const added=await new Promise((r,j)=>new GLTFLoader().parse(extra.buffer.slice(extra.byteOffset,extra.byteOffset+extra.byteLength),'',r,j));if(!isBaseline)composeReef(scene,added.scene);if(!isBaseline){addCompanionFish(scene);refineFish03(scene,{configureMaterial:()=>{}});}scene.updateMatrixWorld(true);
const terrain=[],grid=new Map(),cell=1;
// Independent vertical-triangle index; production routes were sampled by Three raycasts.
scene.traverse(o=>{if(!o.isMesh||/^fish_/.test(o.name))return;terrain.push(o);o.geometry.computeBoundingBox();const a=o.geometry.attributes.position,ix=o.geometry.index;for(let j=0;j<(ix?.count??a.count);j+=3){const v=[0,1,2].map(k=>new T.Vector3().fromBufferAttribute(a,ix?ix.getX(j+k):j+k).applyMatrix4(o.matrixWorld));const [p,q,r]=v,ax=q.x-p.x,az=q.z-p.z,bx=r.x-p.x,bz=r.z-p.z,det=ax*bz-az*bx;if(Math.abs(det)<1e-12)continue;const rec={p,ax,az,bx,bz,ay:q.y-p.y,by:r.y-p.y,det};for(let x=Math.floor(Math.min(...v.map(p=>p.x))/cell);x<=Math.floor(Math.max(...v.map(p=>p.x))/cell);x++)for(let z=Math.floor(Math.min(...v.map(p=>p.z))/cell);z<=Math.floor(Math.max(...v.map(p=>p.z))/cell);z++){const key=x+','+z;if(!grid.has(key))grid.set(key,[]);grid.get(key).push(rec)}}});
function roof(x,z){let y=-Infinity;for(const t of grid.get(Math.floor(x/cell)+','+Math.floor(z/cell))??[]){const dx=x-t.p.x,dz=z-t.p.z,u=(dx*t.bz-dz*t.bx)/t.det,v=(t.ax*dz-t.az*dx)/t.det;if(u>=-1e-8&&v>=-1e-8&&u+v<=1+1e-8)y=Math.max(y,t.p.y+u*t.ay+v*t.by)}return y}
function fishBox(name){const o=scene.getObjectByName(name),inv=o.matrixWorld.clone().invert(),box=new T.Box3();o.traverse(m=>{if(!m.isMesh)return;const a=m.geometry.attributes.position;for(let i=0;i<a.count;i++)box.expandByPoint(new T.Vector3().fromBufferAttribute(a,i).applyMatrix4(m.matrixWorld).applyMatrix4(inv))});return {half:box.getSize(new T.Vector3()).multiply(o.scale).multiplyScalar(.5).addScalar(.05),offset:box.getCenter(new T.Vector3()).multiply(o.scale)}}
function obbSeparated(a,pa,b,pb){const basis=q=>[new T.Vector3(1,0,0),new T.Vector3(0,1,0),new T.Vector3(0,0,1)].map(v=>v.applyQuaternion(q));const aa=basis(pa.quaternion),bb=basis(pb.quaternion),ha=a.half.toArray(),hb=b.half.toArray(),delta=pb.position.clone().add(b.offset.clone().applyQuaternion(pb.quaternion)).sub(pa.position.clone().add(a.offset.clone().applyQuaternion(pa.quaternion)));const axes=[...aa,...bb,...aa.flatMap(x=>bb.map(y=>new T.Vector3().crossVectors(x,y)))];return axes.some(axis=>{if(axis.lengthSq()<1e-10)return false;axis.normalize();const radius=aa.reduce((s,x,i)=>s+ha[i]*Math.abs(axis.dot(x)),0)+bb.reduce((s,x,i)=>s+hb[i]*Math.abs(axis.dot(x)),0);return Math.abs(delta.dot(axis))>radius})}
const saved=JSON.parse(fs.readFileSync(isBaseline?'evidence/life-oct7/baseline-routes.json':'dist/assets/swim-routes.json'));const fish=saved.map((r,i)=>{const curve=new T.CatmullRomCurve3(r.points.map(p=>new T.Vector3(...p)),true,'centripetal');curve.arcLengthDivisions=640;curve.updateArcLengths();return{...r,curve,index:i,bodyHeight:new T.Box3().setFromObject(scene.getObjectByName(r.name)).getSize(new T.Vector3()).y,minClearance:Infinity,maxSpeed:0,minSpeed:Infinity,maxTurn:0}});
const boxes=fish.map(f=>fishBox(f.name));let boundingBoxOverlaps=0;let minPair=Infinity,maxJump=0;const pairMin={};const previous=new Map();
for(let time=0;time<=164;time+=.1){const poses=fish.map(f=>sample(f.curve,time,f.index,f.behavior));for(let i=0;i<fish.length;i++){const f=fish[i],p=poses[i],last=previous.get(f.name);assert.ok(Number.isFinite(p.quaternion.w));assert.ok(Math.abs(p.quaternion.length()-1)<1e-6);if(last){const speed=p.position.distanceTo(last.position)/.1;f.maxSpeed=Math.max(f.maxSpeed,speed);f.minSpeed=Math.min(f.minSpeed,speed);f.maxTurn=Math.max(f.maxTurn,p.quaternion.angleTo(last.quaternion)/.1);maxJump=Math.max(maxJump,p.position.distanceTo(last.position));}previous.set(f.name,p);if(Math.round(time*10)%5===0)for(const[dx,dz]of[[0,0],[.22,0],[-.22,0],[0,.22],[0,-.22]])f.minClearance=Math.min(f.minClearance,p.position.y-roof(p.position.x+dx,p.position.z+dz));for(let j=i+1;j<fish.length;j++){const dist=p.position.distanceTo(poses[j].position);if(dist<1.4&&!obbSeparated(boxes[i],p,boxes[j],poses[j]))boundingBoxOverlaps++;const key=f.name+'/'+fish[j].name;pairMin[key]=Math.min(pairMin[key]??Infinity,dist);minPair=Math.min(minPair,dist)}}}
if(!isBaseline)for(const f of fish){assert.ok(f.minClearance>(f.index<2?.13:.27),f.name+' clearance '+f.minClearance);assert.ok(f.maxTurn<3,f.name+' turn '+f.maxTurn);assert.ok(f.maxSpeed<.9,f.name+' speed '+f.maxSpeed);if(!isBaseline)assert.ok(f.maxSpeed/f.minSpeed>2.3,f.name+' distinct cruise/linger speed');}
if(!isBaseline)assert.equal(boundingBoxOverlaps,0,'conservative animated-fish bounding boxes overlap');if(!isBaseline)assert.ok(pairMin['fish_03/fish_05']>.55,'middle pair separation');if(!isBaseline)assert.ok(pairMin['fish_04/fish_06']>.55,'far pair separation');
const cameras=[{name:'departure',p:[1.5,2.1,4.8],t:[-.5,.8,-6]},{name:'midway',p:[0,2.7,-18],t:[-1.5,1,-31]},{name:'look-back',p:[-3.8,3.6,-36],t:[0,.9,-8]},{name:'low-free-orbit',p:[6,1.1,5],t:[0,.9,0]}];const visibility=[];
for(const c of cameras){const camera=new T.PerspectiveCamera(47,1120/700,.12,140);camera.position.set(...c.p);camera.lookAt(...c.t);camera.updateMatrixWorld(true);const samples=[];for(let time=0;time<90;time+=3){let visible=0,occluded=0;for(const f of fish){const p=sample(f.curve,time,f.index,f.behavior).position;const ndc=p.clone().project(camera);const upper=p.clone().add(new T.Vector3(0,f.bodyHeight/2,0)).project(camera),lower=p.clone().add(new T.Vector3(0,-f.bodyHeight/2,0)).project(camera);if(Math.abs(upper.y-lower.y)*350<8)continue;if(Math.abs(ndc.x)>.94||Math.abs(ndc.y)>.85||ndc.z< -1||ndc.z>1)continue;const ray=new T.Raycaster(camera.position,p.clone().sub(camera.position).normalize(),.12,p.distanceTo(camera.position)-.15);if(ray.intersectObjects(terrain,false).length)occluded++;else visible++}samples.push({time,visible,occluded})}visibility.push({view:c.name,samples,framesWithVisibleFish:samples.filter(s=>s.visible>0).length,occludedSamples:samples.reduce((a,s)=>a+s.occluded,0)})}
if(!isBaseline)assert.ok(visibility[1].framesWithVisibleFish>=20,'midway needs actual in-frustum activity for most sampled times');if(!isBaseline)assert.ok(visibility[2].framesWithVisibleFish>=20,'look-back needs activity');if(!isBaseline)assert.ok(visibility.some(v=>v.occludedSamples>0),'depth occlusion must remain possible');
let middleControlOverlaps=0;
if(!isBaseline){const camera=new T.PerspectiveCamera(47,1120/700,.12,140);camera.position.set(0,2.7,-18);camera.lookAt(-1.5,1,-31);camera.updateMatrixWorld(true);for(let t=0;t<132;t+=.5)for(const f of fish.filter(f=>f.behavior.group==='middle-ledge')){const pose=sample(f.curve,t,f.index,f.behavior),box=boxes[f.index],corners=[];for(const x of [-1,1])for(const y of [-1,1])for(const z of [-1,1])corners.push(new T.Vector3(x*box.half.x,y*box.half.y,z*box.half.z).add(box.offset).applyQuaternion(pose.quaternion).add(pose.position).project(camera));const xs=corners.map(v=>(v.x+1)*560),ys=corners.map(v=>(1-v.y)*350);if(Math.max(...xs)>398&&Math.min(...xs)<724&&Math.max(...ys)>590&&Math.min(...ys)<646)middleControlOverlaps++;}assert.equal(middleControlOverlaps,0,'middle group intersects the fixed-view control bar');}
const result={scope:'Sampled geometry/kinematic checks, not continuous collision proof or biological validation',durationSeconds:164,stepSeconds:.1,fish:fish.map(({curve,points,...f})=>f),minimumPairCenterDistance:minPair,boundingBoxOverlaps,middleControlOverlaps,pairMin,maxStepPer01Second:maxJump,visibility};fs.mkdirSync('evidence/fish-surface-oct7',{recursive:true});fs.writeFileSync('evidence/fish-surface-oct7/'+(isBaseline?'baseline-':'')+'geometry-motion-check.json',JSON.stringify(result,null,2));console.log(JSON.stringify({fish:result.fish,minPair,boundingBoxOverlaps,maxJump,visibility:visibility.map(({samples,...v})=>v)},null,2));
