import {chromium} from 'playwright';import fs from 'node:fs/promises';import path from 'node:path';import {createHash} from 'node:crypto';
const target=process.env.REEF_TARGET;if(target!=='http://127.0.0.1:4173/')throw Error('Isolated branch preview only');
const out=path.resolve('render-evidence');await fs.mkdir(out,{recursive:true});const started=Date.now(),limitMs=320000,hash=b=>createHash('sha256').update(b).digest('hex');
const expected={
  "app.js": "ab28afeb1446c2140d68b6f7f8dbce9b7e1b7e2f2bb32eb79a24f57cc120a3b5",
  "guide-data.js": "72a61b1c7187d930b36205ef8003b1505386609287d52f8b33f52dec79dc2fed",
  "index.html": "b6a4c6e30467547368f5a6e1446e68653d61b56da915999b230989f54f21b605",
  "style.css": "2e0a32cd4f0b38f391dcf4400102ae9dcafe9620b0e32ab6720ef78ce6ff8e95",
  "exhibit-entry.js": "559eb16c198039ab146622cb570c2023e47e607ccf89807e51c8c4ccdd0257d0",
  "scan-exhibit.html": "3dc11caa12012032ccb89727479c8e09415067506e1b80004824bd94aa7950bd",
  "scan-exhibit.css": "7304118c3da1d487bdfd8caf4426c7fcc9d23833c35898a65ea03a9bbf6a3309",
  "scan-exhibit.js": "fbd1f2fcad2ac860e3b94beb697f1dcb296ad4c2f58df029da8eec6cda34a9bb",
  "scan-ocean.js": "bc9fff4201516489e9cb7d552fb2881b580e825c7cca0ebcae647330b499ed09",
  "assets/water-caustics.png": "bd60ac0e3c29ca5ec1cf0d53440fae4e1a97fe0763cdd4314244c46cd7c09c6d",
  "assets/reefs4d/C12019-web.glb": "975228622829cb715ba9b48c0c5cc45c92e8b79d6689102cf188479318362502",
  "scan-route.js": "0fb010683944f827df29f86823aa64e9c10d725633c5fc88377ac45e50909654",
  "scan-life.js": "e4445ff318afb5caa57ac0a013d6c3304141cd01a6d273e2e20443af91805ebe",
  "fish-motion.js": "2204242b56792e1f187db0e9d7577cf4e5039b8249271649d78778edbcecc740",
  "assets/scan-fish.gltf": "d3fb04ded015684f89b8a3c5d549408684e091cea9f0b60cc9df2833aa22bb9f",
  "assets/scan-fish.bin": "d15a8ffacde8529c1ede6d30f3260189d729aafa84c9d4ddf13072ffd7c79457",
  "scan-world.js": "ecded2c574372637c6ed031205e04a6fe91b7523dfdb403cb8dc259ff215a807",
  "assets/scan-world-corals.gltf": "d778d3bf92eb2ddba0f38b7920272c536c75c00cd46ef2f6aa4567871be0474e",
  "assets/scan-world-corals.bin": "92109f208cfe03d4137c17219bd55a5530d67634323565e9a1a6bb155a06de41",
  "artificial-regions.js": "8ec8fbe51226ca9b95f7f2018b38b4c7f35b6ce8da6c55b8b061e98df2d07485",
  "passage.js": "b5e10ede1f41700d358b517b9c708014472ef7a6f33ddc588cdd167f8aadebe5"
};
const report={mode:'exploration-first-arrival',priorScanQA:'37768451006',coverage:'Paused exploration-first arrivals, native learning and exact return, passage landmark projection, near/raw preservation and mobile entry',checkoutCommit:process.env.GITHUB_SHA||null,startedAt:new Date().toISOString(),passed:false,checks:[],captures:[],errors:[],limitations:['Actual browser evidence on a hosted renderer, not user-device/GPU/performance acceptance.','Three spatial frames first: near, wide and mobile. Visual underwater readability requires human review; successful rendering alone is not acceptance.','Reduced motion and device scale factor 1. Water, seabed, light, rocks and particles are uncalibrated synthetic illustration, not collection-site reconstruction or true-color restoration.']};
const save=async()=>{report.elapsedMs=Date.now()-started;await fs.writeFile(path.join(out,'underwater.json'),JSON.stringify(report,null,2)+'\n');};const assert=(x,m)=>{if(!x)throw Error(m)};const equal=(a,b)=>['camera','target'].every(k=>a[k].every((v,i)=>Math.abs(v-b[k][i])<1e-5));let browser,context,page;
const watchdog=setTimeout(async()=>{report.errors.push('320-second continuation budget reached; remaining checks unknown');await save();process.exit(2)},limitMs);
try{
 await save();browser=await chromium.launch({channel:'chromium',headless:true,chromiumSandbox:true,timeout:30000,args:['--enable-automation'],ignoreDefaultArgs:['--enable-unsafe-swiftshader','--disable-gpu-sandbox','--ignore-gpu-blocklist']});const cdp=await browser.newBrowserCDPSession();const cmd=await cdp.send('Browser.getBrowserCommandLine');report.forbiddenFlags=cmd.arguments.filter(x=>['--no-sandbox','--disable-gpu-sandbox','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'].includes(x));assert(!report.forbiddenFlags.length,'Unexpected unsafe graphics/security flag');
 context=await browser.newContext({viewport:{width:1120,height:700},deviceScaleFactor:1,hasTouch:true,reducedMotion:'reduce'});report.sourceHashes={};for(const [file,h]of Object.entries(expected)){assert(hash(await fs.readFile(path.join('dist',file)))===h,'Checkout mismatch: '+file);const r=await context.request.get(new URL(file,target).href,{timeout:10000});assert(r.ok(),'Source request failed: '+file);const served=hash(await r.body());assert(served===h,'Served hash mismatch: '+file);report.sourceHashes[file]=served;}await save();
 page=await context.newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>report.errors.push(String(e)));page.on('console',m=>{if(m.type()==='error')report.errors.push(m.text())});page.on('requestfailed',r=>report.errors.push('Request failed: '+r.url()));page.on('response',r=>{if(r.status()>=400)report.errors.push('HTTP '+r.status()+': '+r.url())});
 const checkpoint=async(name,data={})=>{report.checks.push({name,elapsedMs:Date.now()-started,...data});await save();};const state=()=>page.evaluate(()=>window.reefExhibit?.getState());
 const inspect=async id=>page.evaluate(id=>{const e=document.querySelector(id);if(!e)return {exists:false,id};e.scrollIntoView({block:'nearest',inline:'nearest',behavior:'instant'});const r=e.getBoundingClientRect(),c=getComputedStyle(e),x=(Math.max(0,r.left)+Math.min(innerWidth,r.right))/2,y=(Math.max(0,r.top)+Math.min(innerHeight,r.bottom))/2,hit=document.elementFromPoint(x,y);return {id,exists:true,disabled:!!e.disabled,hidden:e.hidden,visibility:c.visibility,opacity:c.opacity,x,y,rect:{x:r.x,y:r.y,width:r.width,height:r.height,right:r.right,bottom:r.bottom},hit:hit?.id,hitMatches:hit===e||e.contains(hit),inViewport:r.right>0&&r.left<innerWidth&&r.bottom>0&&r.top<innerHeight}},id);
 report.clickEvidence=[];const click=async id=>{const c=await inspect(id);report.clickEvidence.push(c);await save();assert(c.exists&&!c.hidden&&!c.disabled&&c.visibility==='visible'&&Number(c.opacity)>0&&c.inViewport&&c.hitMatches,'Native control not actionable: '+id);await page.mouse.click(c.x,c.y);};
 const waitExhibit=async()=>{await page.waitForFunction(()=>{const e=document.querySelector('#scanError');return window.reefExhibit?.getState().ready||(e&&!e.hidden)},null,{timeout:45000,polling:500});assert(await state(),'Exhibit failed to initialize');};
 const capture=async(file,fullPage=false)=>{await save();await page.screenshot({path:path.join(out,file),fullPage,timeout:25000,animations:'disabled'});report.captures.push({file,sha256:hash(await fs.readFile(path.join(out,file))),state:await state()});await save();};

 await page.goto(new URL('index.html',target).href,{waitUntil:'domcontentloaded',timeout:20000});await page.waitForFunction(()=>window.reef3d?.getState().ready,null,{timeout:80000,polling:500});
 const main=await page.evaluate(()=>reef3d.getState());assert(!main.guide.active&&!main.tour,'Main must arrive paused in exploration');assert(await page.evaluate(()=>document.querySelector('#guideCard').hidden&&getComputedStyle(document.querySelector('footer')).display!=='none'),'Exploration controls hidden');await page.waitForTimeout(500);assert(equal(main,await page.evaluate(()=>reef3d.getState())),'Arrival moved without user');await capture('arrival-main-desktop.png');await checkpoint('main-paused-exploration-arrival',{state:main});
 await page.setViewportSize({width:390,height:740});await capture('arrival-main-mobile.png');await click('#guideEntry');assert(await page.evaluate(()=>reef3d.getState().guide.active&&reef3d.getState().guide.index===0),'Learning did not open');await checkpoint('mobile-native-start-learning');await page.setViewportSize({width:1120,height:700});await click('[data-guide="1"]');await click('#reef');await page.keyboard.press('ArrowRight');const before=await page.evaluate(()=>reef3d.getState());await click('#enterScanExhibit');await page.waitForURL('**/scan-exhibit.html',{timeout:20000});await waitExhibit();
 const entry=await state();assert(entry.route.active&&entry.route.progress===0&&entry.route.goal===0,'Scan route must be paused at entrance');await page.waitForTimeout(500);assert(equal(entry,await state()),'Scan arrival autoplay');assert(!(await inspect('#routeSide')).hidden,'Region navigation hidden');await capture('arrival-scan-desktop.png');await checkpoint('scan-paused-route-arrival',{state:entry});
 await click('#routeSide');const end=await state();assert(end.route.progress===1&&Math.abs(end.camera[2]+60)<.001,'Passage stop not before overhang');const landmark=await page.evaluate(async()=>{const T=await import('./vendor/three.module.js'),a=reefExhibit,o=a.world.group.getObjectByName('Shadowed_Passage_Overhangs'),m=new T.Matrix4();o.getMatrixAt(1,m);const p=new T.Vector3().setFromMatrixPosition(m).applyMatrix4(o.matrixWorld),screen=p.clone().project(a.camera),ray=new T.Raycaster(a.camera.position,p.clone().sub(a.camera.position).normalize()),hit=ray.intersectObject(a.scene,true)[0];return{screen:screen.toArray(),firstObject:hit?.object.name,instance:hit?.instanceId};});assert(landmark.screen.every(v=>Math.abs(v)<1)&&landmark.firstObject==='Shadowed_Passage_Overhangs'&&landmark.instance===1,'Passage landmark not actually visible');await capture('arrival-scan-passage.png');await checkpoint('native-passage-stop-visible-roof',{state:end,landmark});
 await click('#toggleOcean');assert(!(await state()).waterMode,'Route raw unavailable');await click('#toggleOcean');const routeRestored=await state();assert(equal(end,routeRestored)&&routeRestored.route.progress===end.route.progress&&routeRestored.route.active,'Raw round trip changed active route pose or progress');await checkpoint('route-raw-exact-return-preserved',{before:end,after:routeRestored});
 await click('#nearView');const near=await state();assert(!near.route.active&&near.view==='near','Near source view unavailable');await click('#toggleOcean');assert(!(await state()).waterMode,'Raw unavailable');await click('#toggleOcean');assert(equal(near,await state()),'Raw round trip changed near pose');await checkpoint('near-raw-return-preserved');await click('#wideView');await click('#exploreRoute');await page.setViewportSize({width:390,height:740});await capture('arrival-scan-mobile.png');await click('#routeFront');assert((await state()).route.progress===.5,'Mobile region stop inaccessible');await checkpoint('mobile-native-region-navigation');await page.setViewportSize({width:1120,height:700});await click('#returnWorld');await page.waitForFunction(()=>window.reefExhibitReturn?.restored,null,{timeout:85000,polling:500});const after=await page.evaluate(()=>reef3d.getState());assert(equal(before,after)&&after.guide.index===before.guide.index&&after.guide.active&&after.guide.paused&&!after.tour,'Exact guided return failed');await checkpoint('native-return-context-restored',{before,after});
 report.visualAcceptance='Pending human review; geometry and native input evidence do not establish aesthetic acceptance.';report.passed=report.errors.length===0;await save();if(!report.passed)process.exitCode=1;
}catch(e){report.errors.push(String(e?.stack||e));report.passed=false;process.exitCode=1;await save();}
finally{await save();console.log('UNDERWATER_SUMMARY '+JSON.stringify(report));await context?.close().catch(()=>{});await browser?.close().catch(()=>{});clearTimeout(watchdog);}
