from pathlib import Path
import json,hashlib
import numpy as np
from PIL import Image,ImageDraw,ImageFont,ImageFilter,ImageChops
P=Path(__file__).resolve().parent;font=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',21);small=ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf',16)
for pose in ['before','candidate']:
 source=Image.open(P/f'offline-{pose}-passage20-textured.png').convert('RGB');mask=Image.fromarray(np.load(P/f'offline-{pose}-passage20-node66-mask.npy').astype(np.uint8)*255);edge=ImageChops.subtract(mask.filter(ImageFilter.MaxFilter(3)),mask.filter(ImageFilter.MinFilter(3)));source.paste((45,225,230),(0,0),edge);out=Image.new('RGB',(1120,770),(19,28,31));out.paste(source,(0,42));draw=ImageDraw.Draw(out);draw.text((14,9),f'{pose.upper()}: cyan marks node66 only, behind the nearer clump',font=font,fill='white');draw.text((14,748),'Actual object-index outline. The nearer neighboring clump keeps its existing pose; it is outside this change.',font=small,fill='white');out.save(P/f'offline-{pose}-passage20-target-labeled.png')
f=P/'offline-sibling-visual-review.json';d=json.loads(f.read_text());visibility=json.loads((P/'offline-requested-diagnostic-base-visibility.json').read_text());floating=[r for r in visibility['roots']if r['state']=='fully_floating'];assert len(floating)==14 and all(r['object_index_at_projection']==2 for r in floating);d['normal_view_scope']='Node66 is the rear/right-hand target in the nearby group. The more prominent foreground neighboring clump is outside this change; its existing issues are not claimed resolved.';d['requested_diagnostic_occlusion_check']={'floating_baseline_caps':14,'centers_project_to_actual_node66_object_index2':14,'foreground_neighbor_does_not_cover_those_projected_centers':True,'self_occlusion_within_node66_not_excluded':True,'already_buried_cap_centers_on_ground':[8,15],'method_reference':'offline-requested-diagnostic-base-visibility.json','no_additional_camera_chosen':True};f.write_text(json.dumps(d,indent=2)+'\n')
f=P/'offline-sibling-review.md';s=f.read_text();s+='''\n## Explicit neighboring-clump boundary\n\nThe prominent front clump in the normal .2 route view is not node66. It retains its existing pose, and this preview does not claim to fix its grounding. `offline-before-passage20-target-labeled.png` and `offline-candidate-passage20-target-labeled.png` outline only actual visible node66 pixels in cyan.\n\nIn the requested diagnostic source frame, all 14 fully floating basal-cap center projections have actual object-index 2 (node66), so the neighboring foreground clump is not covering those projected centers. Self-occlusion among node66 branches remains possible. The already-buried R08 and R15 cap centers project onto ground, as expected. This is a narrow screen-visibility check; it does not substitute for the continuous cap/ground measurement. No fallback viewpoint was needed.\n''';f.write_text(s)
files={f.name:{'bytes':f.stat().st_size,'sha256':hashlib.sha256(f.read_bytes()).hexdigest()}for f in P.iterdir()if f.name.startswith('offline-') or f.name in ['render_offline_sibling_pose.py','package_offline_sibling_pose.py','check_diagnostic_base_visibility.py','label_scope_and_finalize.py']};files.pop('offline-sibling-artifacts.json',None);(P/'offline-sibling-artifacts.json').write_text(json.dumps(files,indent=2)+'\n')
